In [1]:
import numpy as np

#### numpy's version

In [3]:
print (np.__version__)

1.16.5


In [10]:
mylist = [-17, 4, 0, 5, 9]
myarray = np.array(mylist)
myarray

array([-17,   4,   0,   5,   9])

In [11]:
myarray * 10

array([-170,   40,    0,   50,   90])

#### Promotion of data types  in Numpy
#### within Numpy, every element within an array has to have the same type. 

In [14]:
mytuple = (14, -3.54, 5+7j)

In [15]:
np.array(mytuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

In [13]:
# since an integer can't accommodate a complex number or a floating point number, a floating point number can't accommodate a complex number.
# we need complex numbers for every element within our array.
# therefore, our original integer, floating point, and complex numbers were all promoted to complex numbers

#### difference between python and numpy data structures

In [19]:
mytuple * 5

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [20]:
np.array(mytuple) * 5

array([ 70.  +0.j, -17.7 +0.j,  25. +35.j])

In [21]:
# when we use the asterisk with a python tuple, we're using the asterisk as a replicate operator;
# when we use the asterisk with a Numpy array, we're using it as a mutiplication operator.

### Arange Method

In [29]:
# it is equivalent to range function in python
# numpy.arange([start, ]stop, [step, ]dtype=None)
# starts with zero, and goes up until but not including the number in the parameter
# it returns an ndarray of integers 
# If dtype is not given, infer the data type from the other input arguments.

In [25]:
np.arange(8.4) # return integers as floating data type

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [27]:
np.arange(8) # return integers as integer data type

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
np.arange(10, 23, 5)

array([10, 15, 20])

#### size/length of ndarray

In [31]:
np.arange(8).size # it is an attribute

8

### Linspace()

In [34]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
np.linspace(5, 15, 9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [35]:
np.linspace(5, 15, 9,retstep=True)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [36]:
# from 5 to 15, the difference is 15-5=10. to have 9 steps, the number of intervals is 8.
# so the difference between two steps should be 10/8=1.25

### Zeros and Ones

In [39]:
# numpy.zeros(shape, dtype=float, order='C')
np.zeros((5,4)) # by default, return float64

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.zeros(6) 

array([0., 0., 0., 0., 0., 0.])

In [41]:
# ones is almost as same as zeros
np.ones(5)

array([1., 1., 1., 1., 1.])

### Data types

In [42]:
np.ones(5,dtype='int64')

array([1, 1, 1, 1, 1], dtype=int64)

In [43]:
# https://numpy.org/doc/stable/user/basics.types.html

# Slicing

In [44]:
myvector = np.array([-17, -4, 2, 37, 21, 105])
myvector

array([-17,  -4,   2,  37,  21, 105])

In [45]:
# access one item
myvector[0]

-17

In [47]:
# assign new value
myvector[0] = -20
myvector

array([-20,  -4,   2,  37,  21, 105])

#### create a two dimensional array

In [48]:
myarray = np.arange(35)
myarray.shape = (7,5)
myarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [49]:
myarray[2]

array([10, 11, 12, 13, 14])

In [50]:
myarray[5,2]

27

In [53]:
myarray[5][2]

27

In [52]:
row = 5
column = 2
myarray[row,column]

27

#### create a three dimensional array

In [54]:
myarray = np.arange(70)
myarray.shape = (2,7,5)
myarray

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [55]:
myarray[1,2]

array([45, 46, 47, 48, 49])

In [58]:
myarray[1,2,4]

49

In [59]:
#assign a new value
myarray[1,2,4]=1111
myarray

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48, 1111],
        [  50,   51,   52,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

### Boolean Mask Arrays

In [60]:
myvector = np.array([-17, -4, 2, 37, 21, 105, 0])

In [61]:
zero_mod_7_mask = 0 == (myvector % 7)
zero_mod_7_mask

array([False, False, False, False,  True,  True,  True])

In [63]:
subarray = myvector[zero_mod_7_mask]
subarray

array([ 21, 105,   0])

In [64]:
myvector[0 == (myvector % 7)]

array([ 21, 105,   0])

### Logical Operations

In [65]:
# https://numpy.org/doc/stable/reference/routines.logic.html#logical-operations

In [66]:
zero_mod_7_mask = 0 == (myvector % 7)
postive_test = myvector > 10
combined_mask = np.logical_and (zero_mod_7_mask,postive_test)

In [67]:
myvector[combined_mask]

array([ 21, 105])